---
name: CI-linting

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

jobs:

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Check for non-ASCII characters
        run: |
          output=$(find . -type f \
          \( -name "*.py" -o -name "*.rst" -o -name "*.yml" -o -name "*.toml" \) \
          -exec perl -ne 'print if /[^[:ascii:]]/ && !/latin/i' {} \;)
          if [ -n "$output" ]; then
            echo "Non-ASCII characters found in documentation."
            exit 1
          fi

      - name: Check whether the citation metadata from CITATION.cff is valid
        uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: "--validate"

      - name: Python dependencies
        run: |
          pip install pylint
          pip install pre-commit
          pip install gammasimtools

      - name: Pre-commit
        run: |
          pre-commit run --all-files
